import React,{useState,useEffect} from 'react';
import {ArrowUpRight} from '@phosphor-icons/react';
import {products,categories} from '../data';
import {Button,Label,PageHero,money} from './common';
export function ProductCard({product:p}){return <article className="product-card"><a href={'/catalog/product/'+p.slug+'/'}><div className="product-card-photo"><img src={p.images[0]} alt={p.name} loading="lazy" decoding="async"/><span>{p.origin}</span></div><div className="product-card-body"><small>{p.categoryName}</small><h3>{p.name}</h3><div className="product-price"><span>{money(p.price)}</span><ArrowUpRight size={23}/></div><p>Наличие уточняется</p></div></a></article>}
export function CatalogPreview(){const ids=['325','351','313','294'];return <section className="section catalog-preview"><div className="section-heading"><div><Label>ГОТОВЫЕ МОДЕЛИ</Label><h2>Выберите<br/>из ассортимента.</h2></div><Button dark href="/catalog/">Весь каталог</Button></div><div className="product-grid">{ids.map(id=><ProductCard key={id} product={products.find(p=>p.id===id)}/>)}</div><p className="catalog-note">Заказ от 10 штук. Актуальные остатки, размеры и состав партии подтверждаем до оплаты.</p></section>}
export function Catalog({category='all'}){
 const [filter,setFilter]=useState(category),[search,setSearch]=useState(''),[sort,setSort]=useState('default');
 useEffect(()=>{const load=()=>{const q=new URLSearchParams(window.location.search);setFilter(categories.some(([id])=>id===q.get('category'))?q.get('category'):category);setSearch(q.get('q')||'');setSort(['asc','desc'].includes(q.get('sort'))?q.get('sort'):'default')};load();window.addEventListener('popstate',load);return()=>window.removeEventListener('popstate',load)},[category]);
 function change(key,value){const q=new URLSearchParams(window.location.search);if(value&&value!=='default'&&(value!=='all'||category!=='all'))q.set(key,value);else q.delete(key);window.history.replaceState(null,'',window.location.pathname+(q.size?'?'+q:'')+window.location.hash);if(key==='category')setFilter(value);if(key==='q')setSearch(value);if(key==='sort')setSort(value)}
 const filtered=products.filter(p=>(filter==='all'||p.category===filter)&&((p.name+' '+p.id).toLocaleLowerCase('ru').includes(search.trim().toLocaleLowerCase('ru')))).sort((a,b)=>sort==='asc'?a.price-b.price:sort==='desc'?b.price-a.price:0);
 return <><PageHero label="ГОТОВАЯ ПРОДУКЦИЯ" title={category==='all'?'Каталог одежды и обуви.':categories.find(([id])=>id===category)?.[1]} description="Собственное производство и закупные позиции. Заказ от 10 штук. Остатки и доступные размеры уточняйте перед оплатой." image="real/vest-blue" action={false}/><section className="section catalog-section"><div className="catalog-toolbar"><label>Поиск по названию<input type="search" value={search} onChange={e=>change('q',e.target.value)} placeholder="Костюм, жилет, футболка…"/></label><label>Порядок<select value={sort} onChange={e=>change('sort',e.target.value)}><option value="default">По умолчанию</option><option value="asc">Сначала дешевле</option><option value="desc">Сначала дороже</option></select></label></div><div className="filter-list" aria-label="Категории товаров">{categories.map(([id,name])=><button key={id} type="button" className={filter===id?'active':''} aria-pressed={filter===id} onClick={()=>change('category',id)}>{name}</button>)}</div><p className="catalog-count" aria-live="polite">Найдено: {filtered.length} из {products.length}</p>{filtered.length?<div className="product-grid">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>:<div className="empty-state"><h2>Таких товаров не нашли.</h2><p>Попробуйте другое название или сбросьте фильтры.</p><button className="button black" onClick={()=>{setSearch('');setFilter('all');setSort('default');window.history.replaceState(null,'',window.location.pathname+'?category=all')}}>Показать все товары</button></div>}<div className="catalog-explainer"><p><strong>Собственная и закупная продукция.</strong> Футболки и обувь — закупные, сигнальные жилеты есть в обоих вариантах. Исполнение конкретного сигнального жилета уточняйте у менеджера.</p><p>Для обуви действует скидка от количества. Самовывоз с производства и склада. <a href="/how-to-order/">Условия заказа →</a></p></div></section></>
}
export function ProductPage({product:p}){
 const [active,setActive]=useState(0),[size,setSize]=useState(''),[quantity,setQuantity]=useState('10');
 const number=Number(quantity),valid=Number.isInteger(number)&&number>=10&&number<=100000;
 const request='/how-to-order/?product='+p.id+(size?'&size='+encodeURIComponent(size):'')+'&quantity='+number+'#request';
 return <><section className="section product-detail"><a className="breadcrumb dark" href="/catalog/">Каталог / {p.categoryName}</a><div className="product-layout"><div className="product-gallery"><div className="product-main-photo"><img src={p.images[active]} alt={p.name+' — фото '+(active+1)} fetchPriority="high"/></div><div className="product-thumbnails">{p.images.map((src,i)=><button key={src} type="button" aria-label={'Фото '+(i+1)} aria-pressed={active===i} onClick={()=>setActive(i)}><img src={src} alt="" loading="lazy"/></button>)}</div></div><div className="product-info"><Label>{p.origin}</Label><h1>{p.name}</h1><p className="detail-price">{money(p.price)} <small>за единицу</small></p><p className="availability">Наличие и размеры уточняются</p><p>{p.description}</p><dl className="product-specs">{p.specs.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{p.note&&<p className="product-note">{p.note}</p>}<div className="product-options"><label>Размер<select value={size} onChange={e=>setSize(e.target.value)}><option value="">Уточнить у менеджера</option>{p.sizes.map(s=><option key={s}>{s}</option>)}</select></label><label>Количество<input type="number" min="10" max="100000" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} aria-invalid={!valid}/></label></div>{!valid&&<p role="alert">Укажите целое количество от 10 до 100 000 штук.</p>}{valid?<Button dark href={request}>Уточнить наличие и заказать</Button>:<button className="button black" disabled>Укажите количество</button>}<p className="fine-print">От 10 штук по ассортименту. 100% предоплата после согласования. Срок по ассортименту — до 3 рабочих дней, получение — самовывоз. Состав смешанной партии обсудите с менеджером.</p><a className="text-link" href="/services/branding/">Нужен логотип на одежде? <ArrowUpRight/></a></div></div></section><section className="section related-products"><Label>ИЗ АССОРТИМЕНТА</Label><h2>Дополните заказ.</h2><div className="product-grid">{products.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,4).map(x=><ProductCard key={x.id} product={x}/>)}</div><Button href="/catalog/" dark>Весь каталог</Button></section></>
}
