import React,{useState,useEffect,useRef} from 'react';
import {ArrowRight,Paperclip,DownloadSimple,Copy,EnvelopeSimple} from '@phosphor-icons/react';
import {AVITO,contact,products} from '../data';
import {Button,Label} from './common';
const types={sewing:'Пошив на заказ',catalog:'Товар из каталога',branding:'Нанесение логотипа'};
export default function RequestForm({initialType='sewing',context=''}){
 const [type,setType]=useState(initialType),[selection,setSelection]=useState(''),[qty,setQty]=useState(''),[task,setTask]=useState(context),[files,setFiles]=useState([]),[error,setError]=useState(''),[brief,setBrief]=useState(''),[copied,setCopied]=useState(false);
 const fileInput=useRef(null),result=useRef(null);
 useEffect(()=>{const params=new URLSearchParams(window.location.search),p=products.find(p=>p.id===params.get('product'));if(p){setType('catalog');setSelection(p.name+(params.get('size')?' · размер '+params.get('size'):'')+' · № '+p.id);const n=Number(params.get('quantity'));if(Number.isInteger(n)&&n>0&&n<=100000)setQty(String(n));}else if(types[params.get('type')])setType(params.get('type'));},[]);
 useEffect(()=>{if(brief)result.current?.focus()},[brief]);
 function reset(){setBrief('');setCopied(false);setError('')}
 function attach(e){reset();const list=Array.from(e.target.files||[]);if(list.length>5||list.some(f=>f.size>20*1024*1024||!(/\.(pdf|docx?|jpe?g|png)$/i.test(f.name)))){setError('Выберите до 5 файлов PDF, DOC, DOCX, JPG или PNG, каждый не больше 20 МБ.');e.target.value='';setFiles([]);return;}setFiles(list)}
 function submit(e){e.preventDefault();const v=new FormData(e.currentTarget);const phone=String(v.get('phone')||'');if(phone.replace(/\D/g,'').length<10){setError('Укажите номер телефона с кодом страны.');return;}const name=String(v.get('name')||'').trim();if(!name||!task.trim()){setError('Укажите имя и кратко опишите задачу.');return;}const lines=[types[type],selection&&'Товар: '+selection,'Имя: '+name,'Телефон: '+phone,qty&&'Количество: '+qty,v.get('sizes')&&'Размеры: '+v.get('sizes'),v.get('date')&&'Желаемый срок: '+v.get('date'),v.get('materials')&&'Материалы и лекала: '+v.get('materials'),'Задача: '+task,files.length&&'Файлы (приложить отдельно): '+files.map(f=>f.name).join(', ')];setBrief(lines.filter(Boolean).join('\n'));setError('')}
 function download(){const url=URL.createObjectURL(new Blob([brief],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='beloshveyka-zayavka.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 async function copy(){try{await navigator.clipboard.writeText(brief);setCopied(true)}catch{setError('Не удалось скопировать автоматически. Выделите текст ниже или скачайте заявку.')}}
 return <section className="request section photo-bg" id="request"><Label>ОБСУДИМ ВАШ ЗАКАЗ</Label><h2>От задачи —<br/>к расчёту.</h2><p>Выберите направление и подготовьте описание.<br/>Затем отправьте его нам по почте или через Авито.</p><form onSubmit={submit} onChange={e=>{if(e.target.type!=='file')reset()}}>
 <div className="request-type"><label>Что вам нужно?<select name="type" value={type} onChange={e=>{setType(e.target.value);if(e.target.value!=='catalog')setSelection('')}}>{Object.entries(types).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><p>{type==='catalog'?'Товары из ассортимента — от 10 штук. Наличие уточняется.':type==='sewing'?'Пошив вне ассортимента — от 200 штук. Возможность реализации идеи оценим индивидуально.':'Пришлите макет, материал изделия, тираж и размер нанесения.'}</p></div>
 {selection&&<p className="selected-product">Выбран товар: {selection}</p>}
 <div className="form-grid"><label>Ваше имя<input name="name" required maxLength={100} autoComplete="name" placeholder="Как к вам обращаться?"/></label><label>Телефон<input name="phone" required type="tel" maxLength={30} autoComplete="tel" placeholder="+7 (___) ___-__-__"/></label><label>Количество изделий<input name="quantity" type="number" min="1" max="100000" value={qty} onChange={e=>setQty(e.target.value)} placeholder={type==='sewing'?'От 200 шт.':'От 10 шт.'}/></label><label>Размеры<input name="sizes" maxLength={150} placeholder="Например, 48–54"/></label><label>Желаемый срок<input name="date" type="text" maxLength={100} placeholder="Дата или удобный период"/></label><label>Материалы / лекала<input name="materials" maxLength={200} placeholder="Есть свои / нужна помощь"/></label><label className="wide">Описание задачи<textarea name="task" required maxLength={2000} rows={4} value={task} onChange={e=>setTask(e.target.value)} placeholder="Что нужно изготовить или нанести? Укажите всё, что уже известно."/></label></div>
 <div className="file-row"><button type="button" className="attach" onClick={()=>fileInput.current.click()} aria-describedby="file-help"><Paperclip size={22}/>Выбрать файлы</button><input ref={fileInput} className="file-input" type="file" accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" multiple onChange={attach}/><p id="file-help">До 5 файлов по 20 МБ. Здесь сохраняются только названия.<br/>Сами файлы приложите к письму или сообщению самостоятельно.</p></div>
 {files.length>0&&<ul className="files">{files.map((f,i)=><li key={i}>{f.name}</li>)}</ul>}
 <div className="form-under"><label className="consent"><input type="checkbox" required/><span>Я ознакомлен с <a href="/privacy/">обработкой данных</a> и <a href="/consent/">условиями передачи заявки</a>.</span></label><small>Форма готовит текст в вашем браузере.<br/>Автоматической отправки нет.</small><button className="button" type="submit">Подготовить заявку<ArrowRight size={20}/></button></div>
 {error&&<p role="alert" className="form-error">{error}</p>}
 {brief&&<div className="form-result" role="status" tabIndex={-1} ref={result}><h3>Текст готов. Осталось отправить.</h3><p>Заявка ещё не передана компании. Проверьте текст, откройте письмо или скопируйте его в сообщение. Вложения добавьте отдельно.</p><pre>{brief}</pre><div className="actions"><a className="button" href={'mailto:'+contact.email+'?subject='+encodeURIComponent('Заявка — '+types[type])+'&body='+encodeURIComponent(brief)}>Открыть письмо<EnvelopeSimple/></a><button type="button" className="button outline" onClick={copy}>{copied?'Скопировано':'Скопировать'}<Copy/></button><button type="button" className="button outline" onClick={download}>Скачать текст<DownloadSimple/></button><Button outline href={AVITO} target="_blank" rel="noreferrer">Открыть Авито</Button></div></div>}
 </form><div className="request-rail">Вопросы по заказу: {contact.phone}</div></section>
}
